apiVersion: v1
kind: Service
metadata:
  name: lanchonete-api
  labels:
    app: lanchonete
spec:
  type: LoadBalancer
  selector:
    app: lanchonete
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080