name: Deploy - EKS

on:
  push:
    branches:
      - main
      - feature/**

env:
  REGION_DEFAULT: "sa-east-1"
  CLUSTER_NAME: "eks-lanchonete-api"

jobs:
  deploy:
    name: Deploy EKS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}
      - name: Update Kube Config
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION_DEFAULT }}
            # aws sts get-caller-identity
            # aws sts assume-role --role-arn arn:aws:iam::578360598759:role/role-adm --role-session-name sts
            # aws eks --region sa-east-1 update-kubeconfig --name eks-lanchonete-api
      - name: Kube Apply
        run: |
          kubectl apply -f infra/k8s/lanchonete.yaml
          kubectl apply -f infra/k8s/nodeport.yaml