name: Terraform Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  TF_VAR_accessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_defaultRegion: 'us-east-1'
  TF_VAR_accountId: '638385053556'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Terraform Push Application Docker Image'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: 'us-east-1'
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin \
          638385053556.dkr.ecr.us-east-1.amazonaws.com && \
          docker build -t 638385053556.dkr.ecr.us-east-1.amazonaws.com/lanchonete-api:latest ../ -f . /
          && docker push 638385053556.dkr.ecr.us-east-1.amazonaws.com/lanchonete-api:latest"

